创建ndarray
 1,ndarray中的属性
   shape:纬度
   ndim:维数
   size:元素个数
   dtype:数据类型
   itemsize:每个元素大小


In [1]:
import numpy as np
ndarray=np.array([1,2,3])#一维列表作为参数传入
print(ndarray)
ndarray=np.array([[1,2,3],\
                  [4,5,6]])#多个等长的一维列表作为参数传入
print(ndarray)
#nummpy 自带的初始化函数 zeros()和empty()，纬度以元组形式传入
ndarray=np.zeros(10)
print(ndarray)
ndarray=np.zeros((2,4))
print(ndarray)
ndarray=np.empty((2,3))
print(ndarray)
#ndarray对象中的一些属性
print(ndarray.shape)
print(ndarray.ndim)
print(ndarray.size)
print(ndarray.dtype)
print(ndarray.itemsize)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
(2, 3)
2
6
float64
8


数据类型装换


In [8]:
ndarray=np.array([1.1,2,3.3])
print(ndarray.dtype)
print(ndarray)
ndarray=ndarray.astype(np.int)#数据类型装换
print(ndarray)

float64
[ 1.1  2.   3.3]
[1 2 3]


In [ ]:
数组中的以及与标量之间的计算，索引,切片
数组中的索引与列表最大的区别在于，数组中的索引不再死复制，而是直接在原数组的视图上进行改变（详见书上）

In [19]:
adarray=np.array([1,2,3])
print(ndarray*2)
print(ndarray)
print(ndarray**2)
print(ndarray)
print(ndarray*ndarray)
print(ndarray-ndarray)
print(ndarray)
print(ndarray**0.5)
#一维时索引和切片--------------------------------------------------
print([range(10)])
print(range(10))
#传入range(10)这类集合数据时，list(range(10))和[range(10)]不是同一种结果，前者将逐个分解参数里面的元素，后者直接将参数里面的元素作为一个整体
ndarray=np.array(list(range(10)))
print(ndarray)
print(ndarray[1:10:2])

[[ 0  2  4  6  8 10 12 14 16 18]]
[[0 1 2 3 4 5 6 7 8 9]]
[[ 0  1  4  9 16 25 36 49 64 81]]
[[0 1 2 3 4 5 6 7 8 9]]
[[ 0  1  4  9 16 25 36 49 64 81]]
[[0 0 0 0 0 0 0 0 0 0]]
[[0 1 2 3 4 5 6 7 8 9]]
[[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
   2.44948974  2.64575131  2.82842712  3.        ]]
[range(0, 10)]
range(0, 10)
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


numpy的二维索引和切片
1,二维数组不同维度上的索引用，隔开
例如naarray[0,1]
2,二维数组的切分也可以在各自维度上进行切分
3,还可以将比较得到的boolean值作为索引来访问数组

数组装置和轴对换（此处略）
数组的通用函数


In [27]:
import  math 
print(abs(-1))
print(math.fabs(-1))
ndarray=np.array([1,-1,2])
print(ndarray)
print(abs(ndarray))

1
1.0
[ 1 -1  2]
[1 1 2]


np.where(cond,xarr,yarr)表达式

In [29]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,False,True])
print(np.where(cond,xarr,yarr))

[ 1.1  2.2  1.3  2.4  1.5]


numpy中的数学统计方法
 1，以下函数,用户对数组作为一个集合计算其统计值，这些函数作为数组的一个属性函数存在
   sum(),mean(),str(),var(),min(),max() ,argmin(),argmax()，sort()#sort()函数可以根据传入的参数对数组在不同维度上对数组进行排序

 2，numpy中对数组计算唯一化以及其他的集合操作
   unique(),intersec1d(x,y):计算x,y中的公共元素，并返回有序的结果，union(x,y)，in1d(x,y):，setdiff1d(x,y)
 3,nummpy还支持线性代数中的计算和随机数的生成，详解见书本
