In [ ]:
DataFrame合并
1,merge默认下是'inner'连接,其他连接方式还有'left','right','outer',其中'outer'是左连接和右连接的并集
2,merge函数中有在合并时，有相同列时，用来添加后缀的额函数suffixes()
3,on参数用来连接所按照的列名，当传入多个列名时，用列表表示
4,left_index:在两个DataFrame合并的时候，将左边的DataFrame的index作为连接键与右边的DataFrame
5，层次化的索引略

In [1]:
import pandas as pd
from  pandas import  DataFrame,Series
import  numpy as np

df1=DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2=DataFrame({'key':['a','b','d'],'data2':range(3)})
print("df1:\n",df1)
print("df2:\n",df2)
print("",pd.merge(df1,df2,on='key',how='inner'))

#将索引作为连接键
left1=DataFrame({'key':['a','b','a','a','b','c'],
                 'value':list(range(6))})
right1=DataFrame({'group_val':[3.5,7]},index=['a','b'])
print("left1:\n",left1)
print("right1:\n",right1)
print("pd.merge(left1,right1,left_on='key'),right_index=True:\n",pd.merge(left1,right1,left_on='key',right_index=True))

df1:
    data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b
df2:
    data2 key
0      0   a
1      1   b
2      2   d
    data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
left1:
   key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
right1:
    group_val
a        3.5
b        7.0
pd.merge(left1,right1,left_on='key'),right_index=True:
   key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0


In [ ]:
轴向连接:连接默认是按纵轴扩展连接，如果要横轴扩展连接，应该传入axis=1

In [10]:
#连接数组
arr=np.arange(12).reshape((3,4))
print("arr:\n",arr)
print("pd.concat([arr,arr],axis=1)\n",np.concatenate([arr,arr],axis=1))
#连接pandas对象
s1=Series([0,1],index=['a','b'])
s2=Series([2,3,4],index=['c','d','e'])
s3=Series([5,6],index=['f','g'])
print("pd.concat([s1,s2,s3]):\n",pd.concat([s1,s2,s3]))
print('+,* 操作符在list()中的作用',list(range(5))+list(range(6)))
s4=pd.concat([s1*5,s3])
print("s4:\n",s4)
print("pd",pd.concat([s1,s4],axis=1))
#指定索引
print("pd.concat([s1,s4],axis=1,join_axes=['a','c','b','e'])\n",
      pd.concat([s1,s4],axis=1,join_axes=['a','c','b','e']))

arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
pd.concat([arr,arr],axis=1)
 [[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
pd.concat([s1,s2,s3]):
 a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64
s4:
 a    0
b    5
f    5
g    6
dtype: int64


In [12]:
print(list(range(5))+list(range(6)))

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5]


#combine_first()
a.combine_first(b):
用若a中出现空值，用b总对应索引的值去填充

In [4]:
a=Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],
         index=['f','e','d','c','b','a'])
b=Series(np.arange(len(a),dtype=np.float64),
         index=['f','e','d','c','b','a'])
print("a:\n",a)
print("b:\n",b)
print("b.combine_first(a):\n",b.combine_first(a))
df1=DataFrame({'a':[1,np.nan,5,np.nan],
               'b':[np.nan,2,np.nan,6],
               'c':range(2,18,4)})
df2=DataFrame({'a':[5.,4.,np.nan,5.,np.nan],
               'b':[np.nan,3.,4,6,8]})
print("df1:\n",df1)
print("df2:\n",df2)
print("df1.combine_first(df2):\n",df1.combine_first(df2))

a:
 f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
b:
 f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64
b.combine_first(a):
 f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64
df1:
      a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14
df2:
      a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  5.0  6.0
4  NaN  8.0
df1.combine_first(df2):
      a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  5.0  6.0  14.0
4  NaN  8.0   NaN


In [ ]:
#重塑和轴向旋转
stack():将数据的列转为行
unstack():将数据的行转为列
1，unstack()转换的默认是内层，可以传入参数指定那一层的转换
2，如果不是所有的级别值都能在各分组中找到的话，则unstack()会引入nan值
3，如果对象是DataFrame,则unstack()会创建具有多层结构的列索引

In [14]:
s1=Series([0,1,2,3],index=['a','b','c','d'])
s2=Series([4,5,6],index=['c','d','e'])
print(pd.concat([s1,s2],keys=['one','two'],axis=0).unstack())
data=DataFrame(np.arange(6).reshape((2,3)),
               index=pd.Index(['Ohio','Colorado'],name='state'),
               columns=pd.Index(['one','two','three'],name='number'))
print("data:\n",data)
result=data.stack()
print("result=data.stack(),result:\n",result)
#对DataFrame的unstack()操作
df=DataFrame({'left':result,'right':5+result},
             columns=pd.Index(['left','right'],name='side'))
print("df:\n",df)
print("df.unstack(0):\n",df.unstack(0))

       a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0
data:
 number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5
result=data.stack(),result:
 state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32
df:
 side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10
df.unstack(0):
 side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10


数据装换
1,map()函数用来对集合数据中的元素进行函数运行，属于元素级别上的运算
2，replace()用来替换值
3，duplicated()函数用来得到每一行是否重复，drop_duplicated()则直接丢掉重复的行
4，cut()和qcut()均表示对连续子的区间划分：
  切分得到的对象labels和levels两个属性，前者表示各个数据所在的切分段，后者表示切分出来的具体分段，每一个分段作为一个分段对象存在
   cut():根据传入的切分点，对集合数据进行划分，如果不传入切分点，则根据最大最小值以及传入的切分段的数目进行均分
   qcut():可以根据集合中的分位数进行切分
  



In [24]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats=pd.cut(ages,bins)
print("ages:\n",ages,"\nbins:\n",bins,"\ncats=pd.cut(ages,bins):\n",cats)
# print(cats.categorical)
print("cats.codes:\n",cats.codes)
print("pd.value_counts(cats)\n",pd.value_counts(cats))

ages:
 [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] 
bins:
 [18, 25, 35, 60, 100] 
cats=pd.cut(ages,bins):
 [(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]
cats.codes:
 [0 0 0 1 0 0 2 1 3 2 2 1]
pd.value_counts(cats)
 (18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64


In [ ]:
检测和过滤异常值

In [34]:
np.random.seed(12345)
data=DataFrame(np.random.randn(1000,4))
col=data[3]
# print("col:\n",col)
#any()函数传入的参数0和1不一样，0表示按列判断，最后得到一行数据，1表示按行计算，最后得到一列
print("np.abs(col)>3:\n",(np.abs(data)>3).any(0))

np.abs(col)>3:
 0    True
1    True
2    True
3    True
dtype: bool


In [ ]:
排列和随机采样:permutation()和take()

In [ ]:
计算哑变量:get_dummies()

In [3]:
df=DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
a=pd.get_dummies(df['key'])
print("a=pd.get_dummies(df['key']) a：\n",a)
print("dummiey with data:\n",df.drop('key',axis=1).join(a))

a=pd.get_dummies(df['key']) a：
    a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0
dummiey with data:
    data1  a  b  c
0      0  0  1  0
1      1  0  1  0
2      2  1  0  0
3      3  0  0  1
4      4  1  0  0
5      5  0  1  0
