Pandas中series和字典相比具有如下特点
 1，Series中和字典一样都是具有两个集合，Series具有index和values属性，字典具有key和value,而且两者之间的关系都是关联
 2，Series中对数据的操作更加丰富和灵活，比如字典中的键必须是不可变类型
 3，Series包含丰富的基于Series的集合粒度上的操作

In [4]:
#初始化
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
obj=Series([1,2,3,4,5])
obj1=Series(range(10))
print(obj,"\n",obj1)
print(obj1.index,"\n",obj1.values)

0    1
1    2
2    3
3    4
4    5
dtype: int64 
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
RangeIndex(start=0, stop=10, step=1) 
 [0 1 2 3 4 5 6 7 8 9]


In [9]:
#通过索引值访问Series,

obj.index=['a','b','c','d','e']

print("obj['a']:",obj['a'],"\n","obj[0]: ",obj[0],"\n","obj:","\n",obj)

obj['a']: 1 
 obj[0]:  1 
 obj: 
 a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
python中DataFrame
1,DataFrame可以看成是由一个个seriees组成的
2，DataFrame是一个二维的数据结构，有columns和index分别作为横轴和纵轴的索引，索引是不可改变的，的是可以在初始的时候指定
3，DataFrame还有values()方法，用来返回DataFream中的二维数据

In [21]:
#初始化
data={"first":[1,2,3],"second":[4,5,6]}
data1=np.array([[1,2,3],[4,5,6]])
data_frame1=DataFrame(np.arange(9).reshape((3,3)),index=[1,2,3],columns=["one","two","three"])
print(data_frame1)
print(data1)
data_frame=DataFrame(data,columns=["one","two"])

print(data_frame)

   one  two  three
1    0    1      2
2    3    4      5
3    6    7      8
[[1 2 3]
 [4 5 6]]
Empty DataFrame
Columns: [one, two]
Index: []


In [25]:
#Datafram,Series丢弃：drop()
obj=Series(np.arange(5),index=["a","b","c","d","e"])
newObj=obj.drop("a")
print("before drop:","\n",obj)
print("drop: ","\n",newObj)
data_frame2=DataFrame(np.arange(8).reshape((2,4)),
                      index=["a","b"],
                      columns=["one","two","three","four"])
print("before drop :","\n",data_frame2)
#DataFrame中默认的drop()按index丢弃，若传入axis=1,则按照columns丢弃
print("drop :","\n",data_frame2.drop("a") ,"\n",
       "drop : ","\n",data_frame2.drop("one",axis=1))

before drop: 
 a    0
b    1
c    2
d    3
e    4
dtype: int32
drop:  
 b    1
c    2
d    3
e    4
dtype: int32
before drop : 
    one  two  three  four
a    0    1      2     3
b    4    5      6     7
drop : 
    one  two  three  four
b    4    5      6     7 
 drop :  
    two  three  four
a    1      2     3
b    5      6     7


索引，选取,过滤
1,Series和DataFrame都是可变对象
2,Series中通过切分赋值,(a)如果复制对象是单个的，则Series中在索引中的所有元素都赋值给这个单一的值
(b)如果Series中赋值对象是集合类的，则对应的值按序赋值;但是在list()中赋值对象是不支持非iterable()
对象的，也就是说list()中赋值只能出现(b)那样的情况
3,DataFrame中obj[a]，如果a用字符串输入，则表示按照列（columns）进行索引切分，若输入时数字，则按照行进行切分

In [9]:
#Series
obj=Series(np.arange(4.),index=["a","b","c","d"])
print("obj['b']",obj["b"],"\n","obj[1] : ",obj[1])
#Series中的切片
print("obj[2:4] :",obj[2:4],"\n","obj[['a','b','c']]  :",obj[['a','b','c']])
print(" obj[obj<2]: ",obj[obj<2])
print("obj['a':'c']: ",obj['a':'c'])

#Series中的改变值（重新赋值）
obj["b":"c"]=5
alist=list(np.arange(4))
print(alist)
alist[:2]=[4]#Series中的赋值与list中的赋值，在list中赋值赋值的对象必须是一个iterable的，而Series中则没有这个要求
print("obj: ",obj)
obj[1:3]=[1,2]
print("obj: ",obj)
print("alist: ",alist)

obj['b'] 1.0 
 obj[1] :  1.0
obj[2:4] : c    2.0
d    3.0
dtype: float64 
 obj[['a','b','c']]  : a    0.0
b    1.0
c    2.0
dtype: float64
 obj[obj<2]:  a    0.0
b    1.0
dtype: float64
obj['a':'c']:  a    0.0
b    1.0
c    2.0
dtype: float64
[0, 1, 2, 3]
obj:  a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64
obj:  a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
alist:  [4, 2, 3]


In [23]:
#DataFrame
data=DataFrame(np.arange(16).reshape((4,4)),
               index=["Ohio","Colorado","Utah","New York"],
               columns=["one","two","three","four"])
print("original dataFrame: data\n",data,"\n")
#按照columns（列）进行索引
print("data['one']:\n",       data["one"],"\n",
     "data[['one','two']]:\n",data[["one","two"]])
print("每一列以列的名字作为了DataFrame的一个属性进行访问：data.one\n",data.one)
#通过dataFrame.ix[,]选取行，或者行和列同时进行选择
print("传入数组对row进行索引：data[:2]\n",data[:2])
print("根据布尔型数组选取行：","data[data['one']>5]","\n",data[data["one"]>5])
print("采用ix[]索引：\n")
print("data.ix['Ohio',['two','three']]","\n",data.ix["Ohio",["two","three"]])
print("data.ix['Colorado',:]","\n",data.ix["Colorado",:])
print("data.ix[1,2]","\n",data.ix[1,2])
#icol,irow方法
print("data.icol(1) :\n",data.icol(1))
print("data.irow(0):\n",data.irow(0))
# #Data.frame按照某个轴进行排序
# print("data. :\n",data.reindex(['one']))



#

original dataFrame: data
           one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15 

data['one']:
 Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32 
 data[['one','two']]:
           one  two
Ohio        0    1
Colorado    4    5
Utah        8    9
New York   12   13
每一列以列的名字作为了DataFrame的一个属性进行访问：data.one
 Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32
传入数组对row进行索引：data[:2]
           one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
根据布尔型数组选取行： data[data['one']>5] 
           one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
采用ix[]索引：

data.ix['Ohio',['two','three']] 
 two      1
three    2
Name: Ohio, dtype: int32
data.ix['Colorado',:] 
 one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32
data.ix[1,2] 
 6
data.icol(1) :
 

D:\python3.5.2\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: icol(i) is deprecated. Please use .iloc[:,i]
D:\python3.5.2\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: irow(i) is deprecated. Please use .iloc[i]


In [25]:
#Series ,按index进行对齐，缺失的用nan填充
s1=Series([7.3,-2.5,3.4,1.5],index=["a","c","d","e"])
s2=Series([-1.2,3.6,-1.5,4,3.1],index=["a","c","e","f","g"])
print("s1:\n",s1,"s2:\n",s2)
print("s1+s2:\n",s1+s2)#确实的用填充
#DataFrame，按照index和columns进行对齐，缺失的用nan填充
df1=DataFrame(np.arange(9).reshape((3,3)),
              columns=list("bcd"),
              index=['Ohio','Texas','Coloradio'])
df2=DataFrame(np.arange(12).reshape((4,3)),
              columns=list("bde"),
              index=["Utah","Ohio","Texas","Oregon"])
print("df1:\n",df1)
print("df2:\n",df2)
print("df1+df2:\n",df1+df2)

s1:
 a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64 s2:
 a   -1.2
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64
s1+s2:
 a    6.1
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64
df1:
            b  c  d
Ohio       0  1  2
Texas      3  4  5
Coloradio  6  7  8
df2:
         b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11
df1+df2:
              b   c     d   e
Coloradio  NaN NaN   NaN NaN
Ohio       3.0 NaN   6.0 NaN
Oregon     NaN NaN   NaN NaN
Texas      9.0 NaN  12.0 NaN
Utah       NaN NaN   NaN NaN


In [27]:
df1=DataFrame(np.arange(12).reshape((3,4)),
              columns=list("abcd"))
df2=DataFrame(np.arange(20).reshape((4,5)),
              columns=list("abcde"))
print("df1:\n",df1,"\n","df2:","\n",df2,"\n相加操作会引入空值：df1+df2:\n",df1+df2)
print("相加时指定填充空值：\n",df1.add(df2,fill_value=0))
print("reindex函数时指定不能匹配时应该填充的空值\n",df1.reindex(columns=df2.columns,fill_value=0))

df1:
    a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11 
 df2: 
     a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19 
相加操作会引入空值：df1+df2:
       a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
相加时指定填充空值：
       a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
reindex函数时指定不能匹配时应该填充的空值
    a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0


In [30]:
s1=Series(np.arange(4))
format=lambda x:"%.2f" %x
print("s1.apply(format)\n",s1.apply(format))
print("s1.map(format)\n",s1.map(format))
print("max:",s1.max())
#Dataframe同理

s1.apply(format)
 0    0.00
1    1.00
2    2.00
3    3.00
dtype: object
s1.map(format)
 0    0.00
1    1.00
2    2.00
3    3.00
dtype: object
max: 3


排序和排名:排序时，任何缺失值都会被放到末尾
1,Series主要通过两个方法进行排序，
一个是sort(),其通过Series的内容进行排序；
二是sort_index(),其按照数据的index来进行排序
2，DataFrame的排序

In [43]:
#Series
s=Series([2,1,6,3],index=["a","c","b","d"])
print("s:\n",s)
# s.sort()
s.sort_values()
print("\n s.sort_values():\n",s)
print("\n s.sort_index():",s.sort_index)
#DataFrame
frame=DataFrame(np.arange(8).reshape((2,4)),
                index=["three","one"],
                columns="d a b c".split())
print("frame :\n",frame)
#DataFrame按照索引排序
print("frame.sort_index():\n",frame.sort_index())
#在index和columns上进行排序
print("sort on columns:frame.sort_index(axis=1,ascending=False):\n",frame.sort_index(axis=1,ascending=False))
print("sort on index:frame.sort_index(axis=1,ascending=False)\n",frame.sort_index(axis=0,ascending=False))
#按照某一个列的值对行的位置进行排序
print("sort on  columuns:frame.sort_index(by='b') \n",frame.sort_values(by='b'))
#按照多个列的值一次对行的位置进行排序
print("sort on multi columns:frame.sort_index(by=['a','b'])\n",frame.sort_values(by=['a','b']))
#获取排序之后的排名
s=Series([7,-5,7,4,2,0,4])
print("排序之前：\n",s,"\n排序之后的排名：s.rank(method='min')\n",s.rank(method='min'))
frame=DataFrame({'b':[4.3,7,-3,2],
                'a':[0,1,0,1],
                 'c':[-2,5,8,-2.5]})
print("frame:\n",frame)
print("DataFrame的排名：frame.rank(axis=1,method='min')\n",frame.rank(axis=1,method='min'))

s:
 a    2
c    1
b    6
d    3
dtype: int64

 s.sort_values():
 a    2
c    1
b    6
d    3
dtype: int64

 s.sort_index(): <bound method Series.sort_index of a    2
c    1
b    6
d    3
dtype: int64>
frame :
        d  a  b  c
three  0  1  2  3
one    4  5  6  7
frame.sort_index():
        d  a  b  c
one    4  5  6  7
three  0  1  2  3
sort on columns:frame.sort_index(axis=1,ascending=False):
        d  c  b  a
three  0  3  2  1
one    4  7  6  5
sort on index:frame.sort_index(axis=1,ascending=False)
        d  a  b  c
three  0  1  2  3
one    4  5  6  7
sort on  columuns:frame.sort_index(by='b') 
        d  a  b  c
three  0  1  2  3
one    4  5  6  7
sort on multi columns:frame.sort_index(by=['a','b'])
        d  a  b  c
three  0  1  2  3
one    4  5  6  7
排序之前：
 0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64 
排序之后的排名：s.rank(method='min')
 0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64
frame:
    a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0


In [45]:
s=Series([1,2,3,4],index=['a','a','b','b'])
print("original s:\n",s,
      "\n s['a']\n",s['a'])
frame=DataFrame(np.arange(12).reshape((6,2)),
                index=['a','a','b','b','c','c'])
print("orginal s:\n",s,
      "\n frame.ix['a']:\n",frame.ix['a'])

original s:
 a    1
a    2
b    3
b    4
dtype: int64 
 s['a']
 a    1
a    2
dtype: int64
orginal s:
 a    1
a    2
b    3
b    4
dtype: int64 
 frame.ix['a']:
    0  1
a  0  1
a  2  3


In [5]:
df=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
             index='a b c d'.split(),columns='one two'.split())
print("df :\n",df)
print("df.sum()",df.sum())#得到一行数据，数据是按列进行计算的
print("df.sum(axis=1):\n",df.sum(axis=1))#得到一列数据，数据是按行进行计算得到

df :
     one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
df.sum() one    9.25
two   -5.80
dtype: float64
df.sum(axis=1):
 a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64


In [10]:
from numpy import nan as NA
data=DataFrame([[1.,6.5,3.],[1.,NA,NA],
                [NA,NA,NA],[NA,6.5,3.]])
print("data:\n",data)
print("data.dropna():\n",data.dropna())
print("只丢弃全为nan的行：",data.dropna(how='all'))

data:
      0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
data.dropna():
      0    1    2
0  1.0  6.5  3.0
只丢弃全为nan的行：      0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0


In [ ]:
填充缺失值:fillna()
fillna函数的参数
value:用于填充确实值的标量值或者字典对象(字典对象用来指定哪一行或者哪一列中的空值的特定填充值)
method:填充空值的方法
axis:按行填充还是按列填充
inplace:原址填充还是返回新的DataFrame
limit:对于前向填充或者后向填充，可以连续填充的最大数量

In [ ]:
层次化索引
1,Series和DataFrame中都可以用层次化索引，在初始化时，显然外层索引可能出现重复
2,unstack()和stack()可以将二层索引的Series和二维DataFrame相互装换
3,DataFrame中可以对索引指定名称：dataframe.index.names=[??],data.columns.names=[??]
4,重拍分级顺序 swaplevel("level1.name","levle2.name"):交换层级内外层关系；
  sortlevel("level.name",axis):根据某个级别上的值进行排序,axis用来指定按行还是按列
 sum(level=?,axis=?):按层级和坐标求和





In [ ]:
data=Series(np.random.randn(10),
            index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,1,1,2,3,1,2,2,3]])
print("data:\n",data)
print("data.index:\n",data.index)
#索引
print("data['b']:\n",data['b'])
print("data['a':'c']",data["a":"c"])
print("data.ix[['a','c']]:\n",data.ix[['a','c']])
#在内层中索引
print("data.ix[:,2]:\n",data.ix[:,2])
print("由二层索引Sereies到二维DataFrame:data.unstack()",data.unstack())
print("由二维数组到二层索引的Series之间的转换\n",data.unstack().stack())

In [ ]:
使用DataFrame中的列
set_index()和reset_index:分别表示将DataFrame中的columns转为index;和reset_index则表示将index转为columns

In [13]:
frame=DataFrame({'a':list(range(7)),'b':list(range(7,0,-1)),
                 'c':['one','one','one','two','two','two','two'],
                 'd':[0,1,2,0,1,2,3]})
print("frame:\n",frame)
print("frame.set_index(['c','d']):\n",frame.set_index(['c','d']))
frame=frame.set_index(['c','d'])
print("frame:\n",frame)
print("frame.reset_index():\n",frame.reset_index())

frame:
    a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3
frame.set_index(['c','d']):
        a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1
frame:
        a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1
frame.reset_index():
      c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1
